spring:
  application:
    name: msrvc-users-movies

server:
  port: 8083
  servlet:
    context-path: /users-movies

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: never

# Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      movieService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      movieService:
        maxRetryAttempts: 25
        waitDuration: 10s


# Feign

feign:
  client:
    config:
      msrvc-movies:
        connection-timeout: 5000
        read-timeout: 5000

msrvc:
  movies:
    url: localhost:8084/movies-rating