spring:
  application:
    name: msrvc-users-movies

server:
  port: 8083
  servlet:
    context-path: /users-movies

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: always

# Resilience4j
resilience4j.retry:
    instances:
      movieServiceRetry:
        maxAttempts: 3
        waitDuration: 5s
#        enableExponentialBackoff: true
#        exponentialBackoffMultiplier: 2
        retryExceptions:
          - feign.RetryableException
          - java.net.ConnectException  # Conexões recusadas (Connection Refused)
          - feign.FeignException$FeignServerException  # Erros do servidor (500s)
        ignoreExceptions:
          - feign.FeignException$FeignClientException  # Erros do cliente (4xx)


# Feign

feign:
  client:
    config:
      msrvc-movies:
        connection-timeout: 5000
        read-timeout: 5000

msrvc:
  movies:
    url: localhost:8084/movies-rating