spring:
  application:
    name: msrvc-users-movies

server:
  port: 8083
  servlet:
    context-path: /users-movies

# Actuator
management:
  security:
    enabled:false
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

# Resilience4j
resilience4j:

  # Retry
  retry:
    retryAspectOrder: 2
    instances:
      movieServiceRetry:
        maxAttempts: 3
        waitDuration: 500ms
#        enableExponentialBackoff: true
#        exponentialBackoffMultiplier: 2
        retryExceptions:
          - feign.RetryableException
          - java.net.ConnectException  # Conexões recusadas (Connection Refused)
          - feign.FeignException$FeignServerException  # Erros do servidor (500s)
        ignoreExceptions:
          - feign.FeignException$FeignClientException  # Erros do cliente (4xx)

  # Circuit Breaker
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      movieServiceCb:
          registerHealthIndicator: true
          slidingWindowSize: 6
          minimumNumberOfCalls: 3
          permittedNumberOfFailuresInHalfOpenState: 3
          waitDurationInOpenState: 60s
          failureRateThreshold: 50
          eventConsumerBufferSize: 10

# Feign
feign:
  client:
    config:
      msrvc-movies:
        connection-timeout: 5000
        read-timeout: 5000

msrvc:
  movies:
    url: localhost:8084/movies-rating